// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDnw9JZnGMr_FVru_W4fzM1WSPvJNeoe0',
    appId: '1:267876049339:web:198b660614b616c713e49e',
    messagingSenderId: '267876049339',
    projectId: 'playbus-c7bd9',
    authDomain: 'playbus-c7bd9.firebaseapp.com',
    storageBucket: 'playbus-c7bd9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5cFwfNLVDiVg57aQGs7wvfNVUOPQtML4',
    appId: '1:267876049339:android:3a4e5948aa44c8d413e49e',
    messagingSenderId: '267876049339',
    projectId: 'playbus-c7bd9',
    storageBucket: 'playbus-c7bd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANk41tHeBMyl_LeR9fFwfXymU13d_vmMY',
    appId: '1:267876049339:ios:8bd700be42e4b05313e49e',
    messagingSenderId: '267876049339',
    projectId: 'playbus-c7bd9',
    storageBucket: 'playbus-c7bd9.appspot.com',
    iosClientId: '267876049339-om39nvb6cp4kptislqmnrerhs7j71slb.apps.googleusercontent.com',
    iosBundleId: 'com.example.playbus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANk41tHeBMyl_LeR9fFwfXymU13d_vmMY',
    appId: '1:267876049339:ios:bde8586edff129b613e49e',
    messagingSenderId: '267876049339',
    projectId: 'playbus-c7bd9',
    storageBucket: 'playbus-c7bd9.appspot.com',
    iosClientId: '267876049339-idusoim00tst8f35fd7eebl98s6ipetu.apps.googleusercontent.com',
    iosBundleId: 'com.example.playbus.RunnerTests',
  );
}
